version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      MONGO_DB_URL: "mongodb://mongoDb:27017"
      MONGO_DB_USERNAME: $MONGO_DB_USERNAME
      MONGO_DB_PASSWORD: $MONGO_DB_PASSWORD
      MONGO_DB_DATABASE: $MONGO_DB_DATABASE
      JWT_SECRET: $JWT_SECRET
      JWT_SALT: $JWT_SALT
    depends_on:
      - mongoDb
    networks:
      - network_mongo

  mongoDb:
    container_name: mongoDb
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_DB_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB_DATABASE
    volumes:
      - type: volume
        source: mongo-volume
        target: "/data/db"
        read_only: false
    networks:
      - network_mongo

  mongoExpress:
    container_name: mongoExpress
    image: mongo-express:latest
    ports:
      - 8081:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_DB_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_DB_PASSWORD
      ME_CONFIG_MONGODB_SERVER: mongoDb
    networks:
      - network_mongo
    depends_on:
      - mongoDb

volumes:
  mongo-volume:
    name: mongo-volume

networks:
  network_mongo:
    name: network_mongo
    driver: bridge
